### ISSUE TITLE
Redesign (In Progress)

### ISSUE THREAD

**Issue by TurboProgramming** [Nathan2019/Modern-Calculator#4]
Complete redesign for the app.

**Comment by Nathan2019** [comment]
Code related: Changed Colors In Code Viewer! Tweaked Material Design (All Screens)

**Comment by Nathan2019** [comment]
Redesign Is Still In Progress!

**Comment by Nathan2019** [comment]
I have just noticed this has been assigned to me! Redesign is still in progress then...

**Comment by Nathan2019** [comment]
Redesign is complete!
